#!/bin/bash

set -e

docker build -t n1-rpm -f ./docker/fedora/Dockerfile .
docker run \
 --rm \
 --env NYLAS_GITHUB_OAUTH_TOKEN="$NYLAS_GITHUB_OAUTH_TOKEN" \
 --env N1_DEPLOY_ACCESS_TOKEN="$N1_DEPLOY_ACCESS_TOKEN" \
 --volume="$HOME"/.npm:/root/.npm \
 --volume="$HOME"/.nylas/.apm:/root/.nylas/.apm \
 --volume="$HOME"/.nylas/electron:/root/.nylas/electron \
 n1-rpm /n1/script/rpmbuild
docker rmi n1-rpm
