#!/bin/sh

set -e

script/bootstrap
script/grunt build
script/grunt set-version
script/grunt generate-asar
script/grunt install --install-dir /usr
script/grunt mkrpm --stack --no-color --install-dir /usr
